/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LED_PROTO_LED_COMMAND_PB_H_INCLUDED
#define PB_LED_PROTO_LED_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _led_CommandType {
    /* Write the supplied pattern to the FPGA LED PIO register. */
    led_CommandType_SET_PATTERN = 0,
    /* Read the current FPGA LED PIO register value (pattern field is ignored). */
    led_CommandType_GET_PATTERN = 1
} led_CommandType;

typedef enum _led_StatusCode {
    led_StatusCode_OK = 0, /* Operation succeeded */
    led_StatusCode_ERR_UNKNOWN_CMD = 1, /* command field holds an unrecognised value */
    led_StatusCode_ERR_DECODE_FAIL = 2, /* Incoming packet could not be parsed as LedCommand */
    led_StatusCode_ERR_INVALID_DATA = 3 /* pattern value out of range (reserved for future validation) */
} led_StatusCode;

/* Struct definitions */
typedef struct _led_LedCommand {
    /* Which operation to perform. */
    led_CommandType command;
    /* LED bitmask (0x00–0xFF).  Each bit corresponds to one of the 8 LEDs.
 Ignored for GET_PATTERN commands. */
    uint32_t pattern;
} led_LedCommand;

typedef struct _led_LedResponse {
    /* Result of the operation. */
    led_StatusCode status;
    /* Current LED bitmask after the operation has been applied.
 Equals the written value on SET_PATTERN (confirms the write),
 or the register read-back on GET_PATTERN. */
    uint32_t pattern;
} led_LedResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _led_CommandType_MIN led_CommandType_SET_PATTERN
#define _led_CommandType_MAX led_CommandType_GET_PATTERN
#define _led_CommandType_ARRAYSIZE ((led_CommandType)(led_CommandType_GET_PATTERN+1))

#define _led_StatusCode_MIN led_StatusCode_OK
#define _led_StatusCode_MAX led_StatusCode_ERR_INVALID_DATA
#define _led_StatusCode_ARRAYSIZE ((led_StatusCode)(led_StatusCode_ERR_INVALID_DATA+1))

#define led_LedCommand_command_ENUMTYPE led_CommandType

#define led_LedResponse_status_ENUMTYPE led_StatusCode


/* Initializer values for message structs */
#define led_LedCommand_init_default              {_led_CommandType_MIN, 0}
#define led_LedResponse_init_default             {_led_StatusCode_MIN, 0}
#define led_LedCommand_init_zero                 {_led_CommandType_MIN, 0}
#define led_LedResponse_init_zero                {_led_StatusCode_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define led_LedCommand_command_tag               1
#define led_LedCommand_pattern_tag               2
#define led_LedResponse_status_tag               1
#define led_LedResponse_pattern_tag              2

/* Struct field encoding specification for nanopb */
#define led_LedCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, UINT32,   pattern,           2)
#define led_LedCommand_CALLBACK NULL
#define led_LedCommand_DEFAULT NULL

#define led_LedResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, UINT32,   pattern,           2)
#define led_LedResponse_CALLBACK NULL
#define led_LedResponse_DEFAULT NULL

extern const pb_msgdesc_t led_LedCommand_msg;
extern const pb_msgdesc_t led_LedResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define led_LedCommand_fields &led_LedCommand_msg
#define led_LedResponse_fields &led_LedResponse_msg

/* Maximum encoded size of messages (where known) */
#define LED_PROTO_LED_COMMAND_PB_H_MAX_SIZE      led_LedCommand_size
#define led_LedCommand_size                      8
#define led_LedResponse_size                     8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
