/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "led_command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(led_LedCommand, led_LedCommand, AUTO)


PB_BIND(led_LedResponse, led_LedResponse, AUTO)







