# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: led_command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'led_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11led_command.proto\x12\x03led\"@\n\nLedCommand\x12!\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x10.led.CommandType\x12\x0f\n\x07pattern\x18\x02 \x01(\r\"?\n\x0bLedResponse\x12\x1f\n\x06status\x18\x01 \x01(\x0e\x32\x0f.led.StatusCode\x12\x0f\n\x07pattern\x18\x02 \x01(\r*/\n\x0b\x43ommandType\x12\x0f\n\x0bSET_PATTERN\x10\x00\x12\x0f\n\x0bGET_PATTERN\x10\x01*T\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x13\n\x0f\x45RR_UNKNOWN_CMD\x10\x01\x12\x13\n\x0f\x45RR_DECODE_FAIL\x10\x02\x12\x14\n\x10\x45RR_INVALID_DATA\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'led_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=157
  _globals['_COMMANDTYPE']._serialized_end=204
  _globals['_STATUSCODE']._serialized_start=206
  _globals['_STATUSCODE']._serialized_end=290
  _globals['_LEDCOMMAND']._serialized_start=26
  _globals['_LEDCOMMAND']._serialized_end=90
  _globals['_LEDRESPONSE']._serialized_start=92
  _globals['_LEDRESPONSE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
