#!/usr/bin/env python3
"""
send_led_pattern_pb.py — PC-side protobuf UDP client for the Phase 7.5 LED server.

Sends nanopb-encoded LedCommand messages to led_server_pb running on the DE10-Nano
and decodes LedResponse replies.

Wire protocol (Phase 7.5 protobuf):
  Request:  nanopb-encoded LedCommand  { command, pattern }
  Response: nanopb-encoded LedResponse { status, pattern }

  Defined in:  proto/led_command.proto
  Python stubs: client/led_command_pb2.py  (generated by: make proto)

Usage:
  python3 send_led_pattern_pb.py --host fe80::2833:8aff:fe95:cb3d%enx0... --pattern 0xA5
  python3 send_led_pattern_pb.py --host <board-ip> --get
  python3 send_led_pattern_pb.py --host <board-ip> --animate chase --speed 150
  python3 send_led_pattern_pb.py --host <board-ip> --animate all

The server is led_server_pb (default port 5006).  Use --port 5005 if you repurposed
the original led_server with the protobuf protocol.
"""

import argparse
import socket
import sys
import time

# Import the generated protobuf stubs.
# Run `make proto` in 11_ethernet_hps_led/ if led_command_pb2.py is missing.
try:
    from led_command_pb2 import (
        LedCommand,
        LedResponse,
        CommandType,
        StatusCode,
    )
except ImportError:
    print(
        "Error: led_command_pb2.py not found.\n"
        "Generate it with:  make proto  (from 11_ethernet_hps_led/)\n"
        "Or:  python -m grpc_tools.protoc --proto_path=../proto "
        "--python_out=. ../proto/led_command.proto",
        file=sys.stderr,
    )
    sys.exit(1)

# ── Protocol constants ─────────────────────────────────────────────────────────
DEFAULT_PORT = 5006
TIMEOUT_S    = 2.0

STATUS_NAMES = {
    StatusCode.OK:               "OK",
    StatusCode.ERR_UNKNOWN_CMD:  "ERR_UNKNOWN_CMD",
    StatusCode.ERR_DECODE_FAIL:  "ERR_DECODE_FAIL",
    StatusCode.ERR_INVALID_DATA: "ERR_INVALID_DATA",
}

# ── Named animation sequences ──────────────────────────────────────────────────
ANIMATIONS = {
    "chase": [0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80],
    "breathe": [
        0x01, 0x03, 0x07, 0x0F, 0x1F, 0x3F, 0x7F, 0xFF,
        0x7F, 0x3F, 0x1F, 0x0F, 0x07, 0x03, 0x01, 0x00,
    ],
    "blink": [0xFF, 0x00],
    "stripes": [0xAA, 0x55],
    "all": [
        0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80,
        0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01,
        0x01, 0x03, 0x07, 0x0F, 0x1F, 0x3F, 0x7F, 0xFF,
        0x7F, 0x3F, 0x1F, 0x0F, 0x07, 0x03, 0x01, 0x00,
        0xAA, 0x55, 0xAA, 0x55,
        0xFF, 0x00, 0xFF, 0x00,
    ],
}


def build_request(command: "CommandType.ValueType", pattern: int = 0) -> bytes:
    """Encode a LedCommand as a serialised protobuf byte string."""
    msg = LedCommand()
    msg.command = command
    msg.pattern = pattern & 0xFF
    return msg.SerializeToString()


def parse_response(data: bytes) -> "LedResponse":
    """Decode a serialised LedResponse.  Raises ValueError on failure."""
    resp = LedResponse()
    try:
        resp.ParseFromString(data)
    except Exception as exc:
        raise ValueError(f"Could not parse LedResponse: {exc}") from exc
    return resp


def send_command(
    sock: socket.socket,
    dest: tuple,
    command: "CommandType.ValueType",
    pattern: int = 0,
) -> "LedResponse":
    """Send one LedCommand and return the decoded LedResponse."""
    sock.sendto(build_request(command, pattern), dest)
    raw, _ = sock.recvfrom(256)
    return parse_response(raw)


def status_name(code: int) -> str:
    return STATUS_NAMES.get(code, f"0x{code:02X}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Protobuf UDP client for the DE10-Nano Phase 7.5 LED server.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --host 192.168.1.100 --pattern 0xA5
  %(prog)s --host fe80::2833:8aff:fe95:cb3d%%enx08beac224c03 --get
  %(prog)s --host <board-ip> --animate chase --speed 150
  %(prog)s --host <board-ip> --animate all

Protocol:
  Packets are nanopb-encoded LedCommand / LedResponse messages.
  See proto/led_command.proto for the full schema.
        """,
    )
    parser.add_argument("--host", required=True, help="Board IP address or hostname")
    parser.add_argument(
        "--port", type=int, default=DEFAULT_PORT,
        help=f"UDP port of led_server_pb (default: {DEFAULT_PORT})",
    )
    parser.add_argument("--pattern", help="Hex LED pattern to set, e.g. 0xA5")
    parser.add_argument("--get", action="store_true",
                        help="Read the current LED pattern")
    parser.add_argument(
        "--animate", choices=list(ANIMATIONS),
        help="Run a named animation (loops until Ctrl+C)",
    )
    parser.add_argument(
        "--speed", type=int, default=100,
        help="Animation step interval in ms (default: 100)",
    )
    args = parser.parse_args()

    actions = [args.pattern is not None, args.get, args.animate is not None]
    if sum(actions) != 1:
        parser.error("Specify exactly one of --pattern, --get, or --animate.")

    # Resolve host → address family (IPv4, IPv6 global, or link-local with zone ID)
    try:
        addr_info = socket.getaddrinfo(args.host, args.port,
                                       type=socket.SOCK_DGRAM)
    except socket.gaierror as exc:
        print(f"Error: cannot resolve '{args.host}': {exc}", file=sys.stderr)
        return 1

    af, _, _, _, dest_addr = addr_info[0]
    sock = socket.socket(af, socket.SOCK_DGRAM)
    sock.settimeout(TIMEOUT_S)

    try:
        if args.get:
            resp = send_command(sock, dest_addr, CommandType.GET_PATTERN)
            print(f"Current LED pattern: 0x{resp.pattern:02X} "
                  f"(status: {status_name(resp.status)})")
            return 0 if resp.status == StatusCode.OK else 1

        if args.pattern is not None:
            try:
                value = int(args.pattern, 0) & 0xFF
            except ValueError:
                print(f"Error: invalid pattern '{args.pattern}' — use hex like 0xA5",
                      file=sys.stderr)
                return 1
            resp = send_command(sock, dest_addr, CommandType.SET_PATTERN, value)
            print(f"SET 0x{value:02X} → status={status_name(resp.status)}, "
                  f"LED=0x{resp.pattern:02X}")
            return 0 if resp.status == StatusCode.OK else 1

        # Animation mode
        frames = ANIMATIONS[args.animate]
        step_s = args.speed / 1000.0
        print(f"Running animation '{args.animate}' at {args.speed} ms/step "
              f"(protobuf) — Ctrl+C to stop")
        idx = 0
        while True:
            pattern_val = frames[idx % len(frames)]
            resp = send_command(sock, dest_addr,
                                CommandType.SET_PATTERN, pattern_val)
            if resp.status != StatusCode.OK:
                print(f"Error: server returned {status_name(resp.status)}",
                      file=sys.stderr)
                return 1
            idx += 1
            time.sleep(step_s)

    except KeyboardInterrupt:
        print("\nStopped.")
        try:
            send_command(sock, dest_addr, CommandType.SET_PATTERN, 0x00)
        except Exception:
            pass
        return 0
    except socket.timeout:
        print(f"Error: no response from {args.host}:{args.port} "
              f"(timeout {TIMEOUT_S}s)", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    finally:
        sock.close()

    return 0


if __name__ == "__main__":
    sys.exit(main())
