library ieee;
use ieee.std_logic_1164.all;

--------------------------------------------------------------------------------
-- Top-level wrapper for the Nios II LED demo on the DE10-Nano board.
-- Instantiates the Platform Designer system (nios2_system) and ties the
-- power-on-reset generator into the system reset input.
--------------------------------------------------------------------------------
entity de10_nano_top is
  port (
    fpga_clk1_50 : in  std_logic;
    led          : out std_logic_vector(7 downto 0)
  );
end entity de10_nano_top;

architecture rtl of de10_nano_top is

  -- Platform Designer places the generated system in its own library.
  -- Use a component declaration so the linker resolves it at elaboration.
  component nios2_system is
    port (
      clk_clk                        : in  std_logic;
      led_external_connection_export : out std_logic_vector(7 downto 0);
      reset_reset                    : in  std_logic
    );
  end component nios2_system;

  signal power_on_reset : std_logic;

begin

  -- Power-on reset: holds the system in reset for ~1 ms after power-up
  power_on_reset_generator_inst : entity work.power_on_reset_generator
    generic map (
      G_CLK_FREQ_HZ       => 50_000_000,
      G_RESET_DURATION_NS => 1_000_000
    )
    port map (
      clk_i => fpga_clk1_50,
      por_o => power_on_reset
    );

  -- Nios II system generated by Platform Designer
  nios2_system_inst : nios2_system
    port map (
      clk_clk                        => fpga_clk1_50,
      reset_reset                    => power_on_reset,
      led_external_connection_export => led
    );

end architecture rtl;
