# Timing constraints for the 05_hps_led project.
#
# FPGA_CLK1_50 drives the LED PIO (via clk_0 in Platform Designer) and the
# HPS Lightweight H2F AXI bridge clock input (h2f_lw_axi_clock_clk).
#
# HPS SDRAM timing constraints are generated by the Quartus fitter when the
# altera_hps component is present; they live in
#   output_files/hps_sdram_p0.sdc (auto-included by the flow).

# Primary FPGA clock (50 MHz oscillator on PIN_V11)
# Port name is fpga_clk1_50 — the VHDL top-level wrapper port.
create_clock -name {FPGA_CLK1_50} -period 20.000 [get_ports {fpga_clk1_50}]

# Derive PLL-generated clocks (HPS internal PLLs and any FPGA PLLs)
derive_pll_clocks

# Add uncertainty to all clock-to-clock paths
derive_clock_uncertainty
