# Timing constraints for the 07_hps_interrupts project.
#
# FPGA_CLK1_50 drives the LED PIO, button PIO (via clk_0 in Platform Designer)
# and the HPS Lightweight H2F AXI bridge clock input.
#
# HPS SDRAM timing constraints are generated by the Quartus fitter when the
# altera_hps component is present.

# Primary FPGA clock (50 MHz oscillator on PIN_V11)
create_clock -name {FPGA_CLK1_50} -period 20.000 [get_ports {fpga_clk1_50}]

# Derive PLL-generated clocks (HPS internal PLLs and any FPGA PLLs)
derive_pll_clocks

# Add uncertainty to all clock-to-clock paths
derive_clock_uncertainty
