# Timing constraints for the 15_ddr3_fpga_hps project.
#
# FPGA_CLK1_50 drives all FPGA fabric logic including:
#   - LED PIO
#   - ddr3_test_master (both slave and master interfaces)
#   - HPS Lightweight H2F AXI bridge
#   - HPS F2H SDRAM bridge
#
# HPS SDRAM timing constraints are generated by the Quartus fitter when the
# altera_hps component is present; they live in
#   output_files/hps_sdram_p0.sdc (auto-included by the flow).

# Primary FPGA clock (50 MHz oscillator on PIN_V11)
create_clock -name {FPGA_CLK1_50} -period 20.000 [get_ports {fpga_clk1_50}]

# Derive PLL-generated clocks (HPS internal PLLs)
derive_pll_clocks

# Add uncertainty to all clock-to-clock paths
derive_clock_uncertainty
